name: Run Selenium On GitHub Action
on:
  schedule:
    - cron: '0 */1 * * *'

# # on:
# #   schedule:
# #     - cron: '23 11 * * *'

on:
  workflow_dispatch:

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:
  
jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # - name: Removing previous chrome instances on runner 
      #   run: sudo apt purge google-chrome-stable
        
      # - name: Remove default Chromium
      #   run: sudo apt purge chromium-browser
        
      # - name: Install a new Chromium
      #   run: sudo apt install -y chromium-browser
        
      # - name: Install Chrome
      #   run: |
      #     wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chrome-linux64.zip
      #     unzip chrome-linux64.zip -d chrome-dir  
      #     sudo mv chrome-dir /opt/google/chrome
      #     sudo ln -s /opt/google/chrome/chrome /usr/bin/chrome

      # - name: Install ChromeDriver
      #   run: |
      #     wget -O chromedriver.zip https://chromedriver.storage.googleapis.com/116.0.5845.96./chromedriver_linux64.zip
      #     unzip chromedriver.zip -d chromedriver-dir 
      #     chmod +x chromedriver-dir/chromedriver
      #     sudo mv chromedriver-dir/chromedriver /usr/local/bin/
        
      - name: Removing opencv-python
        run: pip uninstall opencv-python
        
      - name: Installing opencv-headless
        run: pip install opencv-python-headless
        
      - name: Installing all necessary packages
        run: |
          pip install selenium pyyaml pillow imagehash python-dotenv scikit-image webdriver-manager matplotlib

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      # - name: Set up ChromeDriver
      #   uses: nanasess/setup-chrome@v1
      #   with:
      #     version: '116.0.5845.96'
      - name: Configure Git
        run: |
          git config --global user.name "Nagesh Walchatwar"
          git config --global user.email "nageshw.etc19@stvincentnngp.edu.in"
          
      - name: Making lab_latency & direction file writable to github workflow
        run:  chmod +w lab_latency.log

      - name: Running the Timing script
        run: python lab_timing.py
        
      - name: Running rod direction
        run: python rod_direction_lab.py
