name: Run Selenium On GitHub Action

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser

      - name: Installing all necessary packages
        run: |
          pip install selenium pyyaml opencv-python pillow imagehash python-dotenv scikit-image webdriver-manager matplotlib

      - name: Install xvfb
        run: sudo apt-get install xvfb

      - name: Running the Timing script
        run: python lab_timing.py
        
      - name: Running rod direction
        run: python rod_direction_lab.py
