name: Selenium Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pyyaml opencv-python pillow imagehash python-dotenv scikit-image

      
    - name: Install Google Chrome 

      run: |

              chmod +x ./scripts/InstallChrome.sh

                          ./scripts/InstallChrome.sh 
      continue-on-error: true

    - name: Run Selenium script
      run: |
        python lab_selenium.py
